// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQ]QPOOOOQO'#Ci'#CiOOQO'#Cf'#CfQ]QPOOOOQO-E6d-E6d",
  stateData: "n~OPOSQOSROS~OTPOUPOVPOWPOXPO~O",
  goto: "i^PPPPPPPPPP_PPeQRORSRTQOR",
  nodeNames: "⚠ Space Operator Sign Program Number Identifier Annotation Comment Flag",
  maxTerm: 13,
  skippedNodes: [0,1,2,3],
  repeatNodeCount: 1,
  tokenData: "&X~RgX^!jpq!jst#_tu#pz{$[{|$[|}$a}!O$[!P!Q$[!Q![$f!]!^$a!b!c%[!c!}%v#Q#R$[#T#o%v#y#z!j$f$g!j#BY#BZ!j$IS$I_!j$I|$JO!j$JT$JU!j$KV$KW!j&FU&FV!j~!oYP~X^!jpq!j#y#z!j$f$g!j#BY#BZ!j$IS$I_!j$I|$JO!j$JT$JU!j$KV$KW!j&FU&FV!j~#bROs#_st#kt~#_~#pOW~~#sQ!c!}#y#T#o#y~$OSX~!Q![#y!c!}#y#R#S#y#T#o#y~$aOQ~~$fOR~~$kRT~!O!P$t!Q![$f#]#^%V~$wP!Q![$z~%PQT~!Q![$z#]#^%V~%[OT~~%_Q!c!}%e#T#o%e~%jSV~!Q![%e!c!}%e#R#S%e#T#o%e~%{SU~!Q![%v!c!}%v#R#S%v#T#o%v",
  tokenizers: [0],
  topRules: {"Program":[0,4]},
  tokenPrec: 0
})
