// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Space = 1,
  Operator = 2,
  Sign = 3,
  Program = 4,
  Number = 5,
  Identifier = 6,
  Annotation = 7,
  Comment = 8,
  Flag = 9
